version: '3'

services: 
  app:
    image: secret-service:latest
    ports:
      - "8080:8080"
    network_mode: "host"
    depends_on:
      - db

  db:
    image: registry.centos.org/postgresql/postgresql:9.6
    ports:
      - "5432:5432"
    environment: 
      POSTGRESQL_ADMIN_PASSWORD: abcd1234
    networks: 
      - default
